# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-14 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='性别')),
                ('location', models.CharField(choices=[('上海', '上海'), ('北京', '北京'), ('广州', '广州'), ('深圳', '深圳'), ('合肥', '合肥'), ('南京', '南京'), ('西安', '西安')], max_length=16, verbose_name='居住地')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
            ],
        ),
    ]
