# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1990-1-1', verbose_name='出生日期'),
        ),
    ]
